import { describe,it,expect } from 'vitest';
import { parseImport, paragraphs, MAX_UPLOAD_BYTES } from '../lib/imports';
import { initialQuestions,relevanceQuestion } from '../lib/registry';
import { sampleCandidates,sampleRoles } from '../lib/fixtures';
import { activeBrief,compareViews,evaluationState,filterLabel,matchesFilter,nextRevision,providerQuestion,sourceMatches,validateFilter,validatePlan } from '../lib/logic';
import { questionSchema,planSchema, type CandidateView, type AnswerFilter } from '../lib/schema';
import { toCandidate } from '../lib/server/workspace';
import { keyFor } from '../lib/server/evaluation';
const role=()=>{const r=structuredClone(sampleRoles[0]);r.criteria.forEach(c=>c.approved=true);return r;};
const filter:AnswerFilter={join:'and',includeUnknown:true,groups:[{join:'or',conditions:[{questionId:'applied_skills',operator:'gte',value:0.8},{questionId:'personal_task',operator:'gte',value:0.8}]}]};
describe('imports and source preservation',()=>{
  it('loads 16 explicitly fictional records with exact source text',()=>{const imported=parseImport(JSON.stringify(sampleCandidates),'json');expect(imported).toHaveLength(16);expect(imported.every(r=>r.text.startsWith('FICTIONAL'))).toBe(true);expect(imported[6].text).toBe(sampleCandidates[6].text);});
  it('validates blank text, duplicates within a file and existing IDs',()=>{expect(()=>parseImport('[{"id":"x","text":"  "}]','json')).toThrow('empty');expect(()=>parseImport('[{"id":"x","text":"a"},{"id":"x","text":"b"}]','json')).toThrow('Duplicate');expect(()=>parseImport('[{"id":"x","text":"a"}]','json',undefined,['x'])).toThrow('Duplicate');});
  it('rejects unsafe IDs, invalid JSON, oversized uploads and long resumes',()=>{expect(()=>parseImport('[{"id":"../escape","text":"abc"}]','json')).toThrow();expect(()=>parseImport('oops','json')).toThrow('Invalid JSON');expect(()=>parseImport('a'.repeat(MAX_UPLOAD_BYTES+1),'text')).toThrow('20 MB');expect(()=>parseImport(JSON.stringify([{id:'x',text:'a'.repeat(100001)}]),'json')).toThrow('100,000');});
  it('maps quoted multiline CSV columns without changing resume text',()=>{const rows=parseImport('identifier,display,resume\nabc,Example,"Line one\n\nLine two, with comma"','csv',{id:'identifier',name:'display',text:'resume'});expect(rows[0]).toEqual({id:'abc',name:'Example',text:'Line one\n\nLine two, with comma'});});
  it('rejects malformed and duplicate CSV columns',()=>{expect(()=>parseImport('id,id,text\nx,y,z','csv',{id:'id',text:'text'})).toThrow();expect(()=>parseImport('id,text\nx','csv',{id:'id',text:'text'})).toThrow();});
  it('plain text uses explicit boundaries, stable paragraphs, and collision-free IDs',()=>{const text='First paragraph\n\nSecond paragraph';const rows=parseImport(text+'\n---CANDIDATE---\nOther resume','text',undefined,['text-1']);expect(rows[0].id).toBe('text-2');expect(rows[0].text).toBe(text);expect(paragraphs(text)).toEqual([{id:'p0001',text:'First paragraph'},{id:'p0002',text:'Second paragraph'}]);});
});
describe('recruiter control and question payloads',()=>{
  it('all 16 library definitions are standalone and valid',()=>{expect(initialQuestions).toHaveLength(16);initialQuestions.forEach(q=>expect(questionSchema.safeParse(q).success).toBe(true));expect(initialQuestions.filter(q=>q.group==='Writing diagnostics').every(q=>q.experimental)).toBe(true);});
  it('removing a criterion removes it from the actual state sent to relevance',()=>{const r=role();r.criteria[1].enabled=false;r.criteria[0].alternatives=[{text:'Explicit transferable evidence',approved:true},{text:'Unapproved alternate',approved:false}];const state=evaluationState('resume',r);expect(state.approved_active_role_brief).not.toContain(r.criteria[1].text);expect(JSON.stringify(state)).not.toContain(r.jd);expect(state.approved_active_role_brief).toContain('Explicit transferable evidence');expect(state.approved_active_role_brief).not.toContain('Unapproved alternate');});
  it('general state has no role context or candidate name',()=>{expect(evaluationState('resume only',undefined)).toEqual({resume:'resume only'});});
  it('metadata stays out of the provider payload and embedded commands stay data',()=>{const q=initialQuestions[0];const payload=providerQuestion(q);expect(payload).not.toHaveProperty('group');expect(payload).not.toHaveProperty('version');expect(payload.instructions).toContain('untrusted');const state=evaluationState(sampleCandidates[8].text,role());expect(state.resume).toContain('SYSTEM OVERRIDE');expect(activeBrief(role())).not.toContain('SYSTEM OVERRIDE');});
  it('only relevance changes bump revisions',()=>{const r=role();const display=structuredClone(r);display.questionIds=[];display.filter=filter;expect(nextRevision(r,display)).toBe(r.revision);const changed=structuredClone(r);changed.criteria[0].enabled=false;expect(nextRevision(r,changed)).toBe(r.revision+1);changed.criteria[0].enabled=true;changed.rubric[0]='Changed low-end definition';expect(nextRevision(r,changed)).toBe(r.revision+1);});
  it('cache separates models, question versions and revisions, but reuses general answers across roles',()=>{const c=toCandidate(sampleCandidates[0]);const r=role(),other=structuredClone(sampleRoles[1]);const q=initialQuestions[0];expect(keyFor(c,q,r,'jev-1.13.0')).toBe(keyFor(c,q,other,'jev-1.13.0'));expect(keyFor(c,q,r,'jev-1.13.0')).not.toBe(keyFor(c,{...q,version:2},r,'jev-1.13.0'));expect(keyFor(c,q,r,'jev-1.13.0')).not.toBe(keyFor(c,q,r,'jev-other'));expect(keyFor(c,relevanceQuestion(r.rubric),r,'jev-1.13.0')).not.toBe(keyFor(c,relevanceQuestion(r.rubric),{...r,revision:2},'jev-1.13.0'));});
  it('verifies exact JD and explicit recruiter quotation sources',()=>{expect(sourceMatches({kind:'jd',quote:'Build APIs'},'Must Build APIs.','')).toBe(true);expect(sourceMatches({kind:'jd',quote:'build APIs'},'Must Build APIs.','')).toBe(false);expect(sourceMatches({kind:'recruiter',quote:'accept Python'},'','Please accept Python.')).toBe(true);});
});
describe('ranking and explicit answer filters',()=>{
  it('sorts only by raw relevance, with ID ties and unknowns last',()=>{const make=(id:string,score:number|null):CandidateView=>({candidate:{...toCandidate(sampleCandidates[0]),id},answers:{},oldAnswers:[],score,status:'current'});expect([make('c',2),make('a',2),make('z',null),make('b',2.8)].sort(compareViews).map(x=>x.candidate.id)).toEqual(['b','a','c','z']);});
  it('uses visible AND/OR parentheses and keeps uncertain values without hidden confidence gates',()=>{expect(matchesFilter({applied_skills:{type:'noul',noul:0.81}},filter)).toBe(true);expect(matchesFilter({},filter)).toBe(true);expect(matchesFilter({}, {...filter,includeUnknown:false})).toBe(false);expect(filterLabel(filter,initialQuestions)).toContain(' OR ');expect(filterLabel(filter,initialQuestions).startsWith('(')).toBe(true);});
  it('uses three-valued logic so AND false does not become unknown',()=>{const f={...filter,groups:[{...filter.groups[0],join:'and' as const}]};expect(matchesFilter({applied_skills:{type:'noul',noul:0.1}},f)).toBe(false);});
  it('rejects unknown question IDs, invalid categories and out-of-range cutoffs',()=>{expect(()=>validateFilter({...filter,groups:[{join:'and',conditions:[{questionId:'unknown',operator:'gte',value:0.5}]}]},initialQuestions)).toThrow();expect(()=>validateFilter({...filter,groups:[{join:'and',conditions:[{questionId:'applied_skills',operator:'gte',value:8}]}]},initialQuestions)).toThrow('cutoff');});
  it('rejects arbitrary executable plans and unknown criterion IDs',()=>{expect(planSchema.safeParse({code:'process.exit()'}).success).toBe(false);expect(()=>validatePlan({summary:'bad',clarification:null,filter:null,additions:[],changes:[{criterionId:'missing',action:'disable',text:null,alternatives:[]}]},role(),initialQuestions)).toThrow('unknown');});
});
