import { beforeEach,afterEach,describe,it,expect,vi } from 'vitest';
import { mkdtemp,rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { NextRequest } from 'next/server';
import { GET,POST } from '../app/api/[action]/route';
import { readWorkspace,updateWorkspace } from '../lib/server/store';
import { controlRun,requiredQuestions,startRun } from '../lib/server/evaluation';
import { activeBrief } from '../lib/logic';
import type { Proposal, Role } from '../lib/schema';
let folder:string;
beforeEach(async()=>{folder=await mkdtemp(path.join(tmpdir(),'candidate-route-test-'));vi.stubEnv('CANDIDATE_DATA_DIR',folder);vi.stubEnv('TYPESAFE_API_KEY','server-secret-sentinel');vi.stubEnv('OPENROUTER_API_KEY','router-secret-sentinel');vi.stubGlobal('fetch',vi.fn(()=>{throw new Error('Unexpected provider call in route test');}));});
afterEach(async()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();const resolved=path.resolve(folder);if(path.dirname(resolved)!==path.resolve(tmpdir())||!path.basename(resolved).startsWith('candidate-route-test-'))throw new Error('Unsafe cleanup');await rm(resolved,{recursive:true,force:true});});
const request=(action:string,body?:unknown,origin='http://127.0.0.1:3000')=>new NextRequest(`http://localhost:3000/api/${action}`,{method:body===undefined?'GET':'POST',headers:{host:'127.0.0.1:3000',origin,'content-type':'application/json'},...(body===undefined?{}:{body:JSON.stringify(body)})});
const params=(action:string)=>({params:Promise.resolve({action})});
describe('local application routes',()=>{
  it('loads without credentials, makes no provider calls and exposes no keys',async()=>{vi.stubEnv('TYPESAFE_API_KEY','');vi.stubEnv('OPENROUTER_API_KEY','');const response=await GET(request('workspace'),params('workspace'));expect(response.status).toBe(200);const body=await response.json();expect(body.configuration.jev).toBe(false);expect(body.configuration.openrouter).toBe(false);expect(body.run).toBeNull();expect(fetch).not.toHaveBeenCalled();});
  it('accepts matching Host/Origin even when Next normalizes its internal URL',async()=>{const response=await POST(request('samples',{}),params('samples'));expect(response.status).toBe(200);expect(await response.json()).toEqual({imported:16});expect(fetch).not.toHaveBeenCalled();});
  it('blocks cross-origin and nonlocal requests',async()=>{const response=await POST(request('samples',{},'https://attacker.invalid'),params('samples'));expect(response.status).toBe(403);const req=new NextRequest('http://attacker.invalid/api/workspace',{headers:{host:'attacker.invalid'}});expect((await GET(req,params('workspace'))).status).toBe(403);});
  it('validates imports and saves a role through the actual API schema',async()=>{const rejected=await POST(request('import',{content:'[{"id":"x","text":""}]',format:'json'}),params('import'));expect(rejected.status).toBe(400);const state=await (await GET(request('workspace'),params('workspace'))).json();const base=state.roles[0];const edited=structuredClone(base);edited.criteria[0].approved=true;const response=await POST(request('role',{role:edited,base}),params('role'));expect(response.status).toBe(200);expect((await response.json()).revision).toBe(2);});
  it('never includes configured secrets in bootstrap responses',async()=>{const text=await (await GET(request('workspace'),params('workspace'))).text();expect(text).not.toContain('server-secret-sentinel');expect(text).not.toContain('router-secret-sentinel');expect(fetch).not.toHaveBeenCalled();});
  it('accepts an individual worker request but claims no work from a paused run',async()=>{
    await POST(request('samples',{}),params('samples'));
    vi.stubEnv('TYPESAFE_MODEL','jev-latest');
    await updateWorkspace(w=>{w.resolvedModel='jev-1.13.0';w.verifiedRequestedModel='jev-latest';});
    const run=await startRun((await readWorkspace()).roles[0].id);
    await controlRun(run.id,'pause');
    const response=await POST(request('evaluate',{action:'next',runId:run.id}),params('evaluate'));
    expect(response.status).toBe(200);
    expect(await response.json()).toMatchObject({id:run.id,status:'paused',worked:false,processed:0});
    expect(fetch).not.toHaveBeenCalled();
  });
  it('persists the recruiter selection across the full library without provider calls',async()=>{
    const state=await (await GET(request('workspace'),params('workspace'))).json();
    expect(state.questions).toHaveLength(23);
    const base:Role=state.roles[0];
    const edited={...base,questionIds:['customer_work','technical_depth']};
    expect((await POST(request('role',{role:edited,base}),params('role'))).status).toBe(200);
    const reloaded=await readWorkspace();
    const role=reloaded.roles.find(r=>r.id===base.id)!;
    expect(role.questionIds).toEqual(edited.questionIds);
    expect(requiredQuestions(reloaded,role).map(q=>q.id).sort()).toEqual(['assessability','customer_work','technical_depth']);
    expect(role.revision).toBe(base.revision);
    expect(fetch).not.toHaveBeenCalled();
  });
  it('approves an original-library proposal into evaluation and only its approved criterion into relevance',async()=>{
    const state=await (await GET(request('workspace'),params('workspace'))).json();
    const original:Role=state.roles[0];
    const draft={...original,jd:'Work directly with customers.',criteria:[],questionIds:[]};
    const saved=await POST(request('role',{role:draft,base:original}),params('role'));
    const base:Role=await saved.json();
    const question=state.questions.find((q:{id:string})=>q.id==='customer_work');
    const proposal:Proposal={question,reuseQuestionId:question.id,criterion:'Work directly with customers.',status:'required',source:{kind:'jd',quote:'Work directly with customers.'},alternatives:['Internal stakeholder support']};
    const rejected=await POST(request('approve',{roleId:base.id,base,items:[{proposal:{...proposal,source:{kind:'jd',quote:'Invented source'}},useRelevance:true}]}),params('approve'));
    expect(rejected.status).toBe(400);
    expect((await readWorkspace()).roles.find(r=>r.id===base.id)).toEqual(base);
    const response=await POST(request('approve',{roleId:base.id,base,items:[{proposal,useRelevance:true}]}),params('approve'));
    expect(response.status).toBe(200);
    const approved:Role=await response.json();
    expect(approved.questionIds).toEqual(['customer_work']);
    expect(activeBrief(approved)).toContain('Work directly with customers.');
    expect(activeBrief(approved)).not.toContain('Internal stakeholder support');
    expect(requiredQuestions(await readWorkspace(),approved).map(q=>q.id).sort()).toEqual(['assessability','customer_work','role_relevance']);
    expect(fetch).not.toHaveBeenCalled();
  });
});
