'use client';
import { useRef, useState } from 'react';
import { FileUp, Download } from 'lucide-react';
import { Modal } from './modal';
import { MAX_UPLOAD_BYTES, parseCsv } from '@/lib/imports';
export function ImportDialog({onClose,onImport}:{onClose:()=>void;onImport:(body:unknown)=>Promise<void>}) {
  const [content,setContent]=useState('');const [format,setFormat]=useState<'json'|'csv'|'text'>('json');const [columns,setColumns]=useState<string[]>([]);const [mapping,setMapping]=useState({id:'id',name:'name',text:'text'});const [filename,setFilename]=useState('');const [error,setError]=useState('');const [busy,setBusy]=useState(false);const file=useRef<HTMLInputElement>(null);
  function update(text:string,type:typeof format) {setContent(text);setFormat(type);setError('');if(type==='csv') {try {const c=parseCsv(text).columns;setColumns(c);setMapping({id:c.includes('id')?'id':c[0],name:c.includes('name')?'name':'',text:c.includes('text')?'text':c[c.length-1]});}catch(e) {setError((e as Error).message);}}}
  async function read(f:File|undefined) {if(!f) return;if(f.size>MAX_UPLOAD_BYTES) {setError('The upload limit is 20 MB.');return;}const ext=f.name.split('.').pop()?.toLowerCase();if(!['json','csv','txt'].includes(ext??'')) {setError('Choose a JSON, CSV, or plain-text file.');return;}setFilename(f.name);update(await f.text(),ext==='csv'?'csv':ext==='txt'?'text':'json');}
  return <Modal title="Import a candidate pool" onClose={onClose}><div className="modal-body form-stack"><div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void read(e.dataTransfer.files[0]);}}><FileUp size={28}/><strong>{filename||'Bring your resumes into the workspace'}</strong><span>JSON, CSV, or plain text · up to 20 MB</span><button onClick={()=>file.current?.click()}>Choose file</button><input ref={file} type="file" accept=".json,.csv,.txt" hidden onChange={e=>void read(e.target.files?.[0])}/></div><label>Format<select value={format} onChange={e=>update(content,e.target.value as typeof format)}><option value="json">JSON array</option><option value="csv">CSV with headers</option><option value="text">Plain text</option></select></label><label>Or paste source text<textarea rows={7} placeholder={'[{ "id": "c001", "name": "Example", "text": "Resume text…" }]'} value={content} onChange={e=>update(e.target.value,format)}/></label>{format==='csv'&&<div className="form-row">{(['id','name','text'] as const).map(key=><label key={key}>{key==='text'?'Resume text':key==='id'?'Candidate ID':'Name (optional)'}<select value={mapping[key]} onChange={e=>setMapping({...mapping,[key]:e.target.value})}>{key==='name'&&<option value="">None</option>}{columns.map(c=><option key={c}>{c}</option>)}</select></label>)}</div>}{format==='text'&&<p className="small muted">One resume per file, or separate resumes with a line containing <code>---CANDIDATE---</code>. Blank lines are preserved within resumes. IDs are assigned automatically.</p>}<p className="small muted">Use synthetic or authorized data. Records are saved locally; evaluation sends resume text to JEV. PDF and Word imports are outside this version.</p>{error&&<div role="alert" className="error">{error}</div>}<div className="sample-links"><a href="/samples/candidates.json" download><Download size={14}/>Sample JSON</a><a href="/samples/candidates.csv" download><Download size={14}/>Sample CSV</a></div></div><div className="modal-footer"><button onClick={onClose}>Cancel</button><button className="primary" disabled={!content.trim()||busy} onClick={async()=>{setBusy(true);try {await onImport({content,format,...(format==='csv'?{mapping}:{})});onClose();}catch(e) {setError((e as Error).message);}finally {setBusy(false);}}}>{busy?'Importing…':'Import candidates'}</button></div></Modal>;
}
